### ISSUE TITLE
Figure out what tests to subprocess

### ISSUE THREAD

**Issue by altendky** [altendky/qtrio#91]
https://github.com/altendky/qtrio/blob/303788cf5c47880962fb3532752c1048335ca660/qtrio/_tests/test_pytest.py#L28-L41

Various tests are written to subprocess to the real test.  I think there are places this makes sense and more that it probably doesn't.  I think that the single-repo nature here is part of the problem.  We create the basic `qtrio.Runner` feature, then use it in `qtrio.host()` and then use that for running other tests.  The tests of `qtrio.host()` seem likely to belong in subprocesses.  Perhaps they should get a separate run first to make sure they work before running the main test suite and then not subprocess any of the rest of the tests?  (well, unless they have another reason to be subprocessed)

**Comment by altendky** [comment]
@nicoddemus, perhaps you have some useful thoughts here on when to subprocess with `testdir` and when not to?

**Comment by nicoddemus** [comment]
Hi @altendky,

Sorry for the delay, it has been a busy week!

Without knowing the details around the test suite, it is more of a gut feeling: running in subprocesses sometimes is a requirement because we need to change/initialize some global state which we can't really change reliably (or can't unchange for the rest of the test session, violating the principle of test isolation).

**Comment by altendky** [comment]
This got a pass in #126.
